<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHLE30YA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHLE30YA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHLE30YA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHLE30YA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHLE30YA\App_KernelDevDebugContainer([
    'container.build_hash' => 'HLE30YA',
    'container.build_id' => '0f459c5c',
    'container.build_time' => 1685348000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHLE30YA');
